// The sequence of triangle numbers is generated by adding the natural numbers.
// So the 7th triangle number would be: 
// 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 
// Let us list the factors of the first seven triangle numbers:

// 1
// 1,3
// 1,2,3,6
// 1,2,5,10
// 1,3,5,15
// 1,3,7,21
// 1,2,4,7,14,28

// We can see that 28 is the first triangle number to have over five divisors.
// What is the value of the first triangle number to have over five hundred 
// divisors?

// THIS IS SLOW AF
class Highly_Divisible_Traingular_Number
{
    public static void Run()
    {
        ulong total = 0;
        ulong next = 0;
        int targetDivisors = 500;
        int divisors;

        while (true)
        {
            total += ++next;

            divisors = 0;

            // The biggest divisor except for self, will be half of it self
            for (uint i = 1; i <= total / 2; ++i)
            {
                if (total % i == 0)
                    ++divisors;
            }
            ++divisors; // add one for dividing by itself

            if (divisors > targetDivisors)
                break;

        }

        Console.WriteLine($"The triangle {total} is the first triangle with "
        + $"over {targetDivisors} divisors, having {divisors} divisors.");
    }
}