// Multiples_of_3_or_5.Run();
// Even_Fibonacci_Numbers.Run();
// Largest_prime_factor.Run();
// Largest_Palindrome_Product.Run();
// Smallest_Multiple.Run();
// Sum_Square_Difference.Run();
// _10001st_Prime.Run();
// Largest_Product_in_a_Series.Run();
// Special_Pythagorean_Triples.Run();
// Summation_of_Primes.Run();
// Largest_Product_in_a_Grid.Run();
// Highly_Divisible_Traingular_Number.Run();
// Large_Sum.Run();
// Largest_Collatz_Sequence.Run();
// Lattice_Paths.Run();
// Power_Digit_Sum.Run();
// Number_Letter_Counts.Run();
// Maximum_Path_Sum_I.Run();
// Counting_Sundays.Run();
// Factorial_Digit_Sum.Run();
// Amicable_Numbers.Run();
// Names_Scores.Run();
// Non_Abundant_Sums.Run();
// Lexicographic_Permutations.Run();
// _1000_Digit_Fibonacci_Number.Run();
// Reciprocal_Cycles.Run();
//Quadratic_Primes.Run();
Number_Sprial_Diagonals.Run();
