Multiples_of_3_or_5.Run();
Even_Fibonacci_Numbers.Run();
Largest_prime_factor.Run();
Largest_Palindrome_Product.Run();
Smallest_Multiple.Run();
Sum_Square_Difference.Run();
_10001st_Prime.Run();
Largest_Product_in_a_Series.Run();
Special_Pythagorean_Triples.Run();